# Generated by Django 3.2.16 on 2022-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dates',
            field=models.DateField(default='2014-06-25'),
            preserve_default=False,
        ),
    ]
